@server = https://f35cf986trial-sa-wpt-dom-dev-svc-remote-srv.cfapps.us10.hana.ondemand.com
@me = Authorization: Basic {{$processEnv USER}}:


POST {{server}}/kafka-producer/send
Content-Type: application/json
{{me}}

{ "payload": "my big payload" }
